
db.createCollection( "sociaux",
   {
     dep: "string",
     DROIT_red: "number",
     DEPCOM_red: "number",
     CODEPOSTAL_red: "string",
     libcom_red: "string",
     NUMVOIE_red: "string",
     INDREP_red: "number",
     TYPVOIE_red: "string",
     NOMVOIE_red: "string",
     NUMAPPT_red: "number",
     NUMBOITE_red: "number",
     ESC_red: "string",
     COULOIR_red: "string",
     ETAGE_red: "number",
     COMPLIDENT_red: "string",
     ENTREE_red: "string",
     BAT_red: "string",
     IMMEU_red: "string",
     COMPLGEO_red: "string",
     LIEUDIT_red: "string",
     QPV_red: "number",
     TYPECONST_red: "string",
     NBPIECE_red: "number",
    SURFHAB_red: "number",
    CONSTRUCT_red: "number",
    LOCAT_red: "number",
    PATRIMOINE_red: "number",
    ORIGINE_red: "number",
    FINAN_red: "number",
    FINANAUTRE_red: "string",
    CONV_red: "number",
    NUMCONV_red: "string",
    DATCONV_red: "string",
    NEWLOGT_red: "string",
    CUS_red: "number",
    DPEDATE_red: "string",
    DPEENERGIE_red: "string",
    DPESERRE_red: "string",
    SRU_EXPIR_red: "number",
    SRU_ALINEA_red: "number",
    CODSEGPATRIM_red: "string",
    LIBSEGPATRIM_red: "string"
   }
)